### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by ashwanikumar04** [stanfordmlgroup/chexpert-labeler#30]
Hello:

I am trying to install `chexpert-labeler` on Ubuntu machine however, when I run the `step 5`. I am getting following error
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from bllipparser import RerankingParser
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/__init__.py", line 399, in <module>
    from .RerankingParser import RerankingParser, Tree, Sentence, tokenize
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/RerankingParser.py", line 20, in <module>
    from . import JohnsonReranker as reranker
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/JohnsonReranker.py", line 28, in <module>
    _JohnsonReranker = swig_import_helper()
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/JohnsonReranker.py", line 24, in swig_import_helper
    _mod = imp.load_module('_JohnsonReranker', fp, pathname, description)
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/_JohnsonReranker.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev
```

I am not sure what is wrong here.
Can anybody help me here?

Thanks

**Comment by ashwanikumar04** [comment]
I was able to run the labeler on a clean machine
