### ISSUE TITLE
Error encountered on MIMIC：TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ThatNight** [stanfordmlgroup/chexpert-labeler#39]
Hello, I encountered the following error when I tried to use your work for MIMIC data and extract labels.The following error is thrown during the program run, but the program does not stop. I don't know how to solve this error. I am looking forward to your reply.

TypeError: 'NoneType' object is not iterable
  1%|          | 2871/270791 [24:13<56:52:19,  1.31it/s]ERROR:root:Cannot process sentence 140 in 2871
Traceback (most recent call last):
  File ".local/lib/python3.6/site-packages/negbio/pipeline/ptb2ud.py", line 130, in convert_doc
    has_lemmas=self._backend == 'jpype')
TypeError: 'NoneType' object is not iterable

**Comment by llllljm** [comment]
I encountered the same problem as you. Have you solved it？I would appreciate it if you could tell me how to solve this problem.

**Comment by deng1604** [comment]
I encountered the same problem as you. Have you solved it？I would appreciate it if you could tell me how to solve this problem.
```
(chexpert-label) deng@DESKTOP-AHFRTNO:~/Desktop/chexpert-labeler$ python label.py --reports_path ./data/mimic_cxr/reports-only-1-col.csv --output_path ./data/mimic_cxr/reports_labeled.csv --verbose
Loading mention phrases for 14 observations.
Loading unmention phrases for 3 observations.
Extracting mentions...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 276778/276778 [02:51<00:00, 1612.07it/s]
Classifying mentions...
  1%|█▏                                                                                                                                                                                                 | 1749/276778 [1:07:28<273:56:33,  3.59s/it]ERROR:root:Cannot process sentence 202 in 1749
Traceback (most recent call last):
  File "/home/deng/Desktop/NegBio/negbio/pipeline/ptb2ud.py", line 120, in convert_doc
    has_lemmas=self._backend == 'jpype')
TypeError: 'NoneType' object is not iterable
  1%|█▍                                                                                                                                                                                                 | 2035/276778 [1:39:07<807:24:41, 10.58s/it]Killed

```
