### ISSUE TITLE
Error - ValueError: Parser model has not been loaded.

### ISSUE THREAD

**Issue by njan-creative** [stanfordmlgroup/chexpert-labeler#40]
I am getting the below error, when running the label.py

```
  File "/home/user/anaconda3/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/RerankingParser.py", line 786, in check_models_loaded_or_error
    raise ValueError("Parser model has not been loaded.")
ValueError: Parser model has not been loaded.
```
I have already downloaded the stanford-core-nlp jar and the bz2 file for the below.

```
from bllipparser import RerankingParser
RerankingParser.fetch_and_load('GENIA+PubMed')
```

**Comment by jirvin16** [comment]
Sorry that you're having trouble. Can you please share the output of this:
`RerankingParser.fetch_and_load('GENIA+PubMed', verbose=True)`

**Comment by njan-creative** [comment]
Please find the output below.

```
Model directory: /home/user/.local/share/bllipparser/GENIA+PubMed
Model directory already exists, not reinstalling
```
`RerankingParser(unified_model_dir='/home/user/.local/share/bllipparser/GENIA+PubMed')`

**Comment by jirvin16** [comment]
Could you share the entire output (with the full traceback)?

**Comment by njan-creative** [comment]
`Traceback (most recent call last):
  File "label.py", line 53, in <module>
    label(parser.parse_args())
  File "label.py", line 44, in label
    classifier.classify(loader.collection)
  File "/DATA/njan/medical/chexpert/chexpert-labeler/stages/classify.py", line 100, in classify
    self.parser.parse_doc(document)
  File "/home/user/.local/lib/python3.7/site-packages/negbio/pipeline/parse.py", line 55, in parse_doc
    tree = self.parse(text)
  File "/home/user/.local/lib/python3.7/site-packages/negbio/pipeline/parse.py", line 34, in parse
    nbest = self.rrp.parse(str(s))
  File "/home/njan/anaconda3/envs/negbio3.7/lib/python3.7/site-packages/bllipparser/RerankingParser.py", line 614, in parse
    rerank = self.check_models_loaded_or_error(rerank)
  File "/home/njan/anaconda3/envs/negbio3.7/lib/python3.7/site-packages/bllipparser/RerankingParser.py", line 786, in check_models_loaded_or_error
    raise ValueError("Parser model has not been loaded.")
ValueError: Parser model has not been loaded.
`

**Comment by njan-creative** [comment]
Traceback (most recent call last):
  File "label.py", line 53, in <module>
    label(parser.parse_args())
  File "label.py", line 44, in label
    classifier.classify(loader.collection)
  File "/DATA/njan/medical/chexpert/chexpert-labeler/stages/classify.py", line 100, in classify
    self.parser.parse_doc(document)
  File "/home/user/.local/lib/python3.7/site-packages/negbio/pipeline/parse.py", line 55, in parse_doc
    tree = self.parse(text)
  File "/home/user/.local/lib/python3.7/site-packages/negbio/pipeline/parse.py", line 34, in parse
    nbest = self.rrp.parse(str(s))
  File "/home/njan/anaconda3/envs/negbio3.7/lib/python3.7/site-packages/bllipparser/RerankingParser.py", line 614, in parse
    rerank = self.check_models_loaded_or_error(rerank)
  File "/home/njan/anaconda3/envs/negbio3.7/lib/python3.7/site-packages/bllipparser/RerankingParser.py", line 786, in check_models_loaded_or_error
    raise ValueError("Parser model has not been loaded.")
ValueError: Parser model has not been loaded.

**Comment by jirvin16** [comment]
Perhaps try uninstalling and reinstalling the parser? 

The error being thrown is [here,](https://github.com/BLLIP/bllip-parser/blob/master/python/bllipparser/RerankingParser.py#L791) so you could try to debug by looking through that file (specifically starting with [this method](https://github.com/BLLIP/bllip-parser/blob/master/python/bllipparser/RerankingParser.py#L887)).

**Comment by Szh2620** [comment]
hi,i met the same question with you,do you solve it?
