### ISSUE TITLE
ERROR::root:Cannot process sentence 39 in 0

### ISSUE THREAD

**Issue by zoule41** [stanfordmlgroup/chexpert-labeler#48]
'UserWarning: This jar doesn't support universal dependencies, falling back to Stanford Dependencies. To suppress this message, call with universal=False
  warnings.warn("This jar doesn't support universal "
Traceback (most recent call last):
  File "/media/zoule/Elements/chexpert-labeler/chexpert-labeler-master/negbio/pipeline/ptb2ud.py", line 120, in convert_doc
    has_lemmas=self._backend == 'jpype')
  File "/media/zoule/Elements/chexpert-labeler/chexpert-labeler-master/negbio/pipeline/ptb2ud.py", line 172, in convert_dg
    index = text.find(node_form, start)
TypeError: must be str, not java.lang.String'

When I run 'python label.py --reports_path sample_reports.csv', the error will happen. I check the type of text by 'print(type(text))' before 'index = text.find(node_form, start)'. It will print '<class 'str'>. 

I don't know what is the problem and how to fix it.  Can anybody help me?
![error1](https://github.com/stanfordmlgroup/chexpert-labeler/assets/95894798/d7fc8acf-e1be-41b1-b2a2-0aaeea7ed75a)

**Comment by gysabc** [comment]
I had a similar problem, have you solved it yet?
![1](https://github.com/stanfordmlgroup/chexpert-labeler/assets/68911920/7d6415eb-6103-4550-b25d-8f091520896c)
![2](https://github.com/stanfordmlgroup/chexpert-labeler/assets/68911920/3e7e3979-514e-4e12-bac5-0312b6cb9ab7)
![3](https://github.com/stanfordmlgroup/chexpert-labeler/assets/68911920/f828fe40-f8ff-4167-88cd-2ff903ccf47e)
![4](https://github.com/stanfordmlgroup/chexpert-labeler/assets/68911920/e416baac-138d-4a9a-aa01-a5477a0f6464)
![5](https://github.com/stanfordmlgroup/chexpert-labeler/assets/68911920/074b7d1e-41b2-47da-a361-a7e3470dd62f)

**Comment by gysabc** [comment]
> I had a similar problem, have you solved it yet? ![1](https://user-images.githubusercontent.com/68911920/256983964-7d6415eb-6103-4550-b25d-8f091520896c.png) ![2](https://user-images.githubusercontent.com/68911920/256983976-3e7e3979-514e-4e12-bac5-0312b6cb9ab7.png) ![3](https://user-images.githubusercontent.com/68911920/256983980-f828fe40-f8ff-4167-88cd-2ff903ccf47e.png) ![4](https://user-images.githubusercontent.com/68911920/256983984-e416baac-138d-4a9a-aa01-a5477a0f6464.png) ![5](https://user-images.githubusercontent.com/68911920/256983989-074b7d1e-41b2-47da-a361-a7e3470dd62f.png)

to solve this problem，I just use the method below：
https://blog.csdn.net/weixin_46235937/article/details/124520951
